[FEAT] 마이페이지 및 커뮤니티 사이드 메뉴바 구현 (#13)
LikeLion11th-SY-Team/nong-min pull request #15
Opened 2023-08-10 09:57 UTC by ju1e3718

## 관련 이슈
🔒 Closes  

## 작업내용

- [x] 작업 내용
- [ ] 마이페이지, 커뮤니티 뷰에 알맞는 사이드 메뉴바 구현
- [ ] 각 메뉴 항목에 맞는 페이지 이동 경로 지정

|작업 전|작업 후|
|:---:|:---:|
|<img width="250" src="">|<img width="169" alt="스크린샷 2023-08-10 185520" src="https://github.com/LikeLion11th-SY-Team/nong-min/assets/81310250/2437bb6b-1257-4a34-b3a9-a726c5bf5bfe">|

## 추후 진행할 사항

- 메뉴 오른쪽에 들어갈 보드 컴포넌트 구현

## 리뷰포인트

## Reference

## Checklist
- [ ] 필요없는 주석, 프린트문 제거했는지 확인
- [ ] 컨벤션 지켰는지 확인

2023-08-10 15:42 UTC, jh2ee requested changes
p1; 
아래 사항들 반영해서 PR 올려주세요! API 명세 어느정도 확립된 상태라서 미리 로직 구현해놓는게 테스트 하기도 편할 것 같습니다~

2023-08-10 15:42 UTC, jh2ee commented on src/MyPage/MyPageEdit.js
> -function MyPageEdit() {
더미 데이터 생성하는 대신 API 활용해서 로직 구현해놓는게 좋을 것 같아요~

2023-08-10 15:42 UTC, jh2ee commented on src/MyPage/MyPageEdit.js
> +        <Input placeholder="기존 비밀번호 입력" />
비밀번호 확인 로직도 API 반영해서 구현해주세요

2023-08-11 01:16 UTC, ju1e3718 commented
> p1; 아래 사항들 반영해서 PR 올려주세요! API 명세 어느정도 확립된 상태라서 미리 로직 구현해놓는게 테스트 하기도 편할 것 같습니다~

메뉴바만 먼저 하고 데이터 연결하는건 나중에 커밋해서 PR 올리려고 했는데 같이 올리는게 아무래도 좋긴 하겠네요! 반영하도록 하겠습니다~!

2023-08-18 03:59 UTC, merged